https://www.youtube.com/watch?v=9JUAPgtkKpI

https://github.com/patrickloeber/python-engineer-notebooks/blob/master/advanced-python/11-JSON.ipynb

In [9]:
import numpy as np

In [5]:
a=np.array([1,2,3])
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)

[1 2 3]
(3,)
int32
1
3


In [6]:
print(a[0])

1


In [10]:
a[0]=10

In [11]:
print(a)

[10  2  3]


In [12]:
b=a*np.array([2,0,2])

In [14]:
print(b)

[20  0  6]


In [33]:
l=[1,2,3]
a=np.array([1,2,3])
print(l)
print(a)

[1, 2, 3]
[1 2 3]


In [21]:
l.append(4)
print(l)

[1, 2, 3, 4]


In [22]:
a.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [26]:
l=l+[4]
print(l)

[1, 2, 3, 4]


In [31]:
a=a+np.array([4])
print(a)

[5 6 7]


In [34]:
a=a+np.array([4,4,4])
print(a)

[5 6 7]


In [17]:
l=[1,2,3]
a=np.array([1,2,3])

In [38]:
l=l*2
print(l)

[1, 2, 3, 1, 2, 3]


In [18]:
a=a*2
print(a)

[2 4 6]


In [43]:
a=np.sqrt(a)
print(a)

[1.         1.41421356 1.73205081]


In [46]:
a=np.log(a)
print(a)

[0.         0.69314718 1.09861229]


In [ ]:
l1=[1,2,3]
l2=[4,5,6]
a=np.array([1,2,3])

#dot product

In [13]:
l1=[1,2,3]
l2=[4,5,6]

In [14]:
#dot product 
dot=0
for i in range(len(l1)):
       dot=l1[i]*l2[i]
print(dot)    

18


In [20]:
a1=np.array(l1)
a2=np.array(l2)
print(a1)
print(a2)

[1 2 3]
[4 5 6]


In [21]:
dot=np.dot(a1,a2)
print(dot)

32


In [26]:
sum1=a1*a2
print(sum1)

[ 4 10 18]


In [27]:
dot=np.sum(sum1)
print(dot)

32


In [29]:
dot=(a1*a2).sum()
print(dot)

32


In [31]:
dot=a1@a2
print(dot)

32


In [32]:
dot=a1@a2
print(dot)

32


speed test 

In [33]:
from timeit import default_timer as timer

In [42]:
# speed test lists vs array
from timeit import default_timer as timer

a = np.random.randn(1000)
b = np.random.randn(1000)

A = list(a)
B = list(b)

T = 10

def dot1():
    dot = 0
    for i in range(len(A)):
        dot += A[i]*B[i]
    return dot

def dot2():
    return np.dot(a,b)

start = timer()
for t in range(T):
    dot1()
end = timer()
t1 = end-start

start = timer()
for t in range(T):
      dot2()
end = timer()
t2 = end-start

print('Time with lists:', t1)
print('Time with array:', t2)
print('Ratio', t1/t2)

Time with lists: 0.001239399891346693
Time with array: 6.200000643730164e-05
Ratio 19.99031875262873


In [43]:
a=np.random.randn(10)

In [46]:
print(type(a))
print(a)

<class 'numpy.ndarray'>
[-0.52892827  0.865775    1.54876884  0.06422344 -0.24594952  2.31592357
  0.68228856  1.66556213 -0.50783077 -0.27842283]


In [47]:
a=np.array([1,2])

In [48]:
print(a.shape)

(2,)


Multidimensional

In [51]:
a=np.array([[1,2],[3,4]])

In [52]:
print(a)
print(a.shape)

[[1 2]
 [3 4]]
(2, 2)


In [53]:
# row first, then columns
print(a[0])#first row
print(a[0][0])#
print(a[0,0])

[1 2]
1
1


In [65]:
a=np.array([[1,2,5],[3,4,10]])

In [66]:
print(a)
print(type(a))
print(a.shape)

[[ 1  2  5]
 [ 3  4 10]]
<class 'numpy.ndarray'>
(2, 3)


In [67]:
# row first, then columns
print(a[0])#first row
print(a[0][0])#row 1 col 1 
print(a[0,0])

[1 2 5]
1
1


In [68]:
# slicing
print(a[:,0]) # all rows in col 0
print(a[0,:]) # all columns in row 0

[1 3]
[1 2 5]


In [69]:
# transpose
print(a.T)

[[ 1  3]
 [ 2  4]
 [ 5 10]]


In [73]:
# Array indexing
# Slicing: Similar to Python lists, numpy arrays can be sliced.
# Since arrays may be multidimensional, you must specify a slice for each 
# dimension of the array:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Integer array indexing
b = a[0,1]
print(b)

# Slicing
row0 = a[0,:]
print(row0)

col0 = a[:, 0]
print(col0)

slice_a = a[0:2,1:3]
print(slice_a)

# indexing starting from the end: -1, -2 etc...
last = a[-1,-1]
print(last)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[1 2 3 4]
[1 5 9]
[[2 3]
 [6 7]]
12


In [77]:
b=a[-1]
print(b)

[ 9 10 11 12]


In [78]:
b=a[-1,-1]
print(b)

12


In [89]:
# Boolean indexing:
a = np.array([[1,2,10], [3, 4,12], [5, 6,-1]])
print(a)

[[ 1  2 10]
 [ 3  4 12]
 [ 5  6 -1]]


In [90]:
# same shape with True or False for the condition
bool_idx = a > 2
print(bool_idx)

[[False False  True]
 [ True  True  True]
 [ True  True False]]


In [91]:
# note: this will be a rank 1 array!
print(a[bool_idx])

[10  3  4 12  5  6]


In [92]:
# We can do all of the above in a single concise statement:
print(a[a > 2])

[10  3  4 12  5  6]


In [93]:
# np.where(): same size with modified values
b = np.where(a>2, a, -1)
print(b)

[[-1 -1 10]
 [ 3  4 12]
 [ 5  6 -1]]


In [98]:
# fancy indexing: access multiple indices at once
a = np.array([10,19,30,41,50,61])
print(a)
b = a[[1,3,5]]
print(b)

[10 19 30 41 50 61]
[19 41 61]


In [99]:
b=[1,3,5]
print(a[b])

[19 41 61]


In [100]:
even=np.argwhere(a%2==0).flatten()

In [101]:
print(a[even])

[10 30 50]


In [102]:
a_even = a[even]
print(a_even)

[10 30 50]


In [105]:
# reshape
a = np.arange(1, 7)
print(a)
print(a.shape)

[1 2 3 4 5 6]
(6,)


In [104]:
b = a.reshape((2, 3)) # error if shape cannot be used
print(b)

[[1 2 3]
 [4 5 6]]


In [107]:
b=a.reshape((3,2))
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [108]:
print(a.shape)
d = a[np.newaxis, :]
print(d)
print(type(d))
print(d.shape)

(6,)
[[1 2 3 4 5 6]]
<class 'numpy.ndarray'>
(1, 6)


In [110]:
b=a[:,np.newaxis]
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [111]:
# concatenation
a = np.array([[1, 2], [3, 4]])
print(a)
b = np.array([[5, 6]])
print(b)


[[1 2]
 [3 4]]
[[5 6]]
[1 2 3 4 5 6]


In [112]:
c = np.concatenate((a, b))
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [113]:
c = np.concatenate((a, b),axis=0)
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [114]:
c = np.concatenate((a, b),axis=None)
print(c)

[1 2 3 4 5 6]


In [115]:
c = np.concatenate((a, b),axis=1)
print(c)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [116]:
e = np.concatenate((a, b.T), axis=1)
print(e)

[[1 2 5]
 [3 4 6]]


In [118]:
# hstack: Stack arrays in sequence horizontally (column wise). needs a tuple
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.hstack((a,b))
print(type(c))
print(c)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8]


In [119]:
# vstack: Stack arrays in sequence vertically (row wise). needs a tuple
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.vstack((a,b))
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [120]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.vstack((a,b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [121]:
# broadcasting
# Broadcasting is a powerful mechanism that allows numpy to work with arrays of 
# different shapes when performing arithmetic operations.
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y) 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [128]:
# data science functions and axes
a = np.array([[7,8,9,10,11,12,13], [17,18,19,20,21,22,23]])
print(a)

[[ 7  8  9 10 11 12 13]
 [17 18 19 20 21 22 23]]


In [123]:
print(a.sum(axis=None)) # overall sum

210


In [124]:
print(a.sum())

210


In [125]:
print(a.sum(axis=0)) # along the rows -> 1 sum entry for each column

[24 26 28 30 32 34 36]


In [126]:
print(a.sum(axis=1)) # along the columns -> 1 sum entry for each row

[ 70 140]


In [129]:
print(a.mean(axis=0))

[12. 13. 14. 15. 16. 17. 18.]


In [130]:
print(a.mean(axis=None))

15.0


In [131]:
print(a.mean(axis=None)) # overall mean
print(a.mean())
print(a.mean(axis=0)) # along the rows -> 1 mean entry for each column
print(a.mean(axis=1)) # along the columns -> 1 mean entry for each row

15.0
15.0
[12. 13. 14. 15. 16. 17. 18.]
[10. 20.]


In [132]:
print(a.var())

29.0


In [133]:
print(a.std(axis=1))

[2. 2.]


In [134]:
print(np.max(a,axis=None))

23


In [136]:
# datatypes
# https://numpy.org/devdocs/user/basics.types.html
# Let numpy choose the datatype
x = np.array([1, 2])
print(x.dtype)#datatype

int32


In [137]:
x = np.array([1.0, 2.0])
print(x.dtype)#datatype

float64


In [138]:
# Force a particular datatype, how many bits (how precise)
x = np.array([1, 2], dtype=np.int64) # 8 bytes
print(x.dtype)

int64


In [140]:
# Force a particular datatype, how many bits (how precise)
x = np.array([1.0, 2.0], dtype=np.int64) # 8 bytes
print(x.dtype)

int64


In [139]:
x = np.array([1, 2], dtype=np.float32) # 4 bytes
print(x.dtype)

float32


In [141]:
# Force a particular datatype, how many bits (how precise)
x = np.array([1.0, 2.0], dtype=np.float32) # 8 bytes
print(x.dtype)

float32


In [142]:
# Force a particular datatype, how many bits (how precise)
x = np.array([1.0, 2.0], dtype=np.float64) # 8 bytes
print(x.dtype)

float64


In [143]:
# Force a particular datatype, how many bits (how precise)
x = np.array([1.0, 2.0], dtype=np.float16) # 8 bytes
print(x.dtype)

float16


In [146]:
# copy
a = np.array([1,2,3])
b = a # only copies reference! modifys both arrays
b[0] = 42
print(a)

[42  2  3]


In [145]:
a = np.array([1,2,3])
b = a.copy() # actual copy!
b[0] = 42
print(a)

[1 2 3]


In [149]:
# generating data
a = np.zeros((2,3)) # size as tuple
b = np.ones((2,3))
print(a)
print(a.dtype)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
float64
[[1. 1. 1.]
 [1. 1. 1.]]


In [150]:
a=np.full((2,3),5.0)
print(a)

[[5. 5. 5.]
 [5. 5. 5.]]


In [155]:
# specific value
c = 5 * np.ones((3,3))
print(c)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [154]:
# specific value
c = 5 * np.ones((3,3),dtype=np.int32)
print(c)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [156]:
# identity
d = np.eye(3) #3x3
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [157]:
# identity
d = np.eye(3,dtype=np.int32) #3x3
print(d)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [158]:
# arange
e = np.arange(10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [160]:
a=np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [161]:
# linspace
f = np.linspace(0, 10, 5)
print(f)

[ 0.   2.5  5.   7.5 10. ]


In [162]:
# random numbers
a = np.random.random((3,2)) # uniform 0-1 distribution
print(a)

[[0.73112943 0.5050788 ]
 [0.17484584 0.87297348]
 [0.67482736 0.64078312]]


In [163]:
b = np.random.randn(3,2) # normal/Gaussian distribution, mean 0 and unit variance
# no tuple as shape here! each dimension one argument
print(b)

[[ 1.59952379 -1.11710324]
 [ 1.74625949 -0.25249523]
 [-0.59215714 -0.56793519]]


In [164]:
R = np.random.randn(10000)
print(R.mean(), R.var(), R.std())

0.0018628940845723673 1.011694152398252 1.0058300812752876


In [166]:
R = np.random.randn(10, 3)
print(R)
print(R.mean()) # mean of whole array

[[ 2.01122693  1.41106295 -1.47118528]
 [-0.23048612 -0.39413464 -0.81004037]
 [-0.55281581 -0.45299103  1.79273543]
 [ 2.30740683 -0.90065744  0.09000857]
 [ 0.03662761  1.5063298   0.7236615 ]
 [-2.48258077 -1.48524344  1.32724104]
 [ 0.20128102  0.22117689 -0.25174974]
 [-1.68168711  0.80515697 -0.41776774]
 [-0.89588119  0.47780167  2.0186697 ]
 [-0.15958709 -1.32030654 -1.14446349]]
0.009293636179853727


In [167]:
# random integer, low,high,size; high is exclusive
R = np.random.randint(3,10,size=(3,3)) # if we only pass one parameter, then from 0-x
print(R)

[[5 8 8]
 [4 6 8]
 [8 5 5]]


In [169]:
# with integer is between 0 up to integer exclusive
c = np.random.choice(5, size=10)
print(c)

[0 1 2 3 0 0 4 2 0 0]


In [170]:
# with integer is between 0 up to integer exclusive
c = np.random.choice([-8,-7,-6], size=10)
print(c)

[-6 -8 -6 -8 -7 -6 -8 -7 -6 -7]


In [171]:
# with an array it draws random values from this array
d = np.random.choice([1,2,3,4], size=8)
print(d)

[3 4 3 3 2 2 2 3]


In [173]:
# eigenvalues
a = np.array([[1,2], [3,4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
# Note: use eigh if your matrix is symmetric (faster)
print(a)
print(eigenvalues)
print(eigenvectors) # column vectors
print(eigenvectors[:,0]) # column 0 corresponding to eigenvalue[0]

[[1 2]
 [3 4]]
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[-0.82456484  0.56576746]


In [174]:
# verify: e-vec * e-val = A * e-vec
d = eigenvectors[:,0] * eigenvalues[0]
e = a @ eigenvectors[:, 0]
print(d, e)
print(d == e) # numerical issues

# correct way to compare matrix
print(np.allclose(d,e))

[ 0.30697009 -0.21062466] [ 0.30697009 -0.21062466]
[ True False]
True


In [175]:
# solve linear system
# x1+x2=2200
# 1.5 x1 + 4 x2 = 5050
# 2 equations and 2 unknowns
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200,5050])

# Ax = b <=> x = A-1 b

# But: inverse is slow and less accurate
x = np.linalg.inv(A).dot(b) # not recommended
print(x)
x = np.linalg.solve(A,b) # good
print(x)

[1500.  700.]
[1500.  700.]


In [176]:
# loading from csv
# https://www.python-engineer.com/videos/how-to-load-data/

# 1) load with np.loadtxt()
# skiprows=1
data = np.loadtxt(FILE_NAME, delimiter=",",dtype=np.float32)
print(data.shape, data.dtype)

# 2) load with np.genfromtxt()
# skip_header=0, missing_values="---", filling_values=0.0
data = np.genfromtxt(FILE_NAME, delimiter=",", dtype=np.float32)
print(data.shape)

NameError: name 'FILE_NAME' is not defined